import { parseArgs } from "@std/cli/parse-args";

const args = parseArgs(Deno.args, {
    boolean: ["dev", "d", "package", "clean"],
    alias: { d: "dev" },
});

const isDev = args.dev || args.d || false;
const shouldPackage = args.package || !isDev;
const cleanOnly = args.clean || false;

const outDir = isDev ? "dist/dev" : "dist/release";

// 1. Clean Output Directories
async function clean(): Promise<void> {
    try {
        await Deno.remove("build", { recursive: true });
    } catch {
        /* ignore */
    }
    try {
        await Deno.remove(outDir, { recursive: true });
    } catch {
        /* ignore */
    }
    console.log(`✓ Cleaned ${outDir} and build/`);
}

if (cleanOnly) {
    await clean();
    Deno.exit(0);
}

await clean();

// 2. Prepare Directories
await Deno.mkdir(`${outDir}/vendor`, { recursive: true });
await Deno.mkdir(`${outDir}/src/styles`, { recursive: true });
await Deno.mkdir(`${outDir}/src/chat/gemini/styles`, { recursive: true });

// 3. Generate Typed Environment Module (src/env.ts)
const manifestRaw = await Deno.readTextFile("src/manifest.json");
const manifest = JSON.parse(manifestRaw);
const baseVersion = manifest.version || "0.1.3";

const now = new Date();
const pad = (n: number) => String(n).padStart(2, "0");
const buildTimestamp = `${now.getFullYear().toString().slice(-2)}${pad(now.getMonth() + 1)}${pad(now.getDate())}.${
    pad(now.getHours())
}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
const buildVersion = isDev ? `${baseVersion}-dev.${buildTimestamp}` : baseVersion;

const envFileContent = `// Automatically generated by build.ts - DO NOT EDIT MANUALLY
export const __DEV__: boolean = ${isDev};
export const __BUILD_VERSION__: string = "${buildVersion}";
`;
await Deno.writeTextFile("src/env.ts", envFileContent);
console.log(`✓ Generated src/env.ts (__DEV__ = ${isDev}, version = "${buildVersion}")`);

// 4. Copy Vendor & Stylesheet Assets
try {
    await Deno.copyFile("vendor/katex.min.css", `${outDir}/vendor/katex.min.css`);
} catch (e) {
    console.warn("Notice: vendor/katex.min.css copy skipped:", e);
}

try {
    await Deno.copyFile("src/styles/globals.css", `${outDir}/src/styles/globals.css`);
    await Deno.copyFile("src/chat/gemini/styles/gemini.css", `${outDir}/src/chat/gemini/styles/gemini.css`);
} catch (e) {
    console.warn("Notice: stylesheet copy skipped:", e);
}

// 5. Generate Manifest
manifest.version = baseVersion;
manifest.description = isDev ? `[DEV ${buildTimestamp}] ${manifest.description}` : manifest.description;

manifest.content_scripts = [
    {
        matches: ["https://gemini.google.com/*", "https://duck.ai/*"],
        css: ["vendor/katex.min.css", "src/styles/globals.css"],
        run_at: "document_start",
    },
    {
        matches: ["https://gemini.google.com/*"],
        css: ["src/chat/gemini/styles/gemini.css"],
        js: ["content.js"],
        run_at: "document_start",
    },
];

manifest.web_accessible_resources = [
    {
        resources: [
            "app.js",
            "*.js",
            "src/chat/gemini/styles/gemini.css",
        ],
        matches: ["https://gemini.google.com/*", "https://duck.ai/*"],
    },
];

await Deno.writeTextFile(`${outDir}/manifest.json`, JSON.stringify(manifest, null, 2));

// 6. Bundle with Native Deno 2 Bundle (Code-Splitting)
console.log(`Bundling with native deno bundle (${isDev ? `DEV: ${buildVersion}` : `PROD: ${buildVersion}`})...`);

const bundleArgs = [
    "bundle",
    "--platform",
    "browser",
    "--code-splitting",
    "--outdir",
    outDir,
];

if (isDev) {
    bundleArgs.push("--sourcemap", "inline");
} else {
    bundleArgs.push("--minify");
}

bundleArgs.push("src/entrypoints/app.ts");

const bundleCmd = new Deno.Command("deno", {
    args: bundleArgs,
});
const bundleOutput = await bundleCmd.output();

if (bundleOutput.code !== 0) {
    const errorText = new TextDecoder().decode(bundleOutput.stderr);
    console.error("Bundle failed:\n", errorText);
    Deno.exit(bundleOutput.code);
}

console.log(`✓ Successfully bundled app.js and split chunks into ${outDir}`);

// 7. Write MV3 Dynamic Import Bootloader (content.js)
const bootloaderCode = `// Dynamic Import Bootloader for WebExtension MV3
(async () => {
  try {
    const src = (typeof chrome !== "undefined" && chrome.runtime?.getURL)
      ? chrome.runtime.getURL("app.js")
      : "./app.js";
    await import(src);
  } catch (err) {
    console.error("[AI Chat UI] Bootloader failed to load app.js:", err);
  }
})();
`;
await Deno.writeTextFile(`${outDir}/content.js`, bootloaderCode);
console.log(`✓ Created dynamic bootloader: ${outDir}/content.js`);

// 8. Package Release Archive via 7z
if (shouldPackage) {
    const zipFileName = isDev ? `ai-chat-ui-${buildVersion}.zip` : `ai-chat-ui-${baseVersion}.zip`;

    try {
        const p7zCmd = new Deno.Command("7z", {
            args: ["a", "-tzip", "-mx=9", "-aoa", "-bd", zipFileName, "."],
            cwd: outDir,
        });
        const { code: p7zCode } = await p7zCmd.output();
        if (p7zCode === 0) {
            console.log(`✓ Created release archive via 7z: ${outDir}/${zipFileName}`);
        } else {
            console.warn("Warning: 7z exited with non-zero code, archive skipped");
        }
    } catch (e) {
        console.warn("Notice: 7z command unavailable, zip packaging skipped:", e);
    }
}
