import { parseArgs } from "@std/cli/parse-args";
import { compile, optimize } from "@kuboon/tailwindcss-deno";
import { Scanner } from "@tailwindcss/oxide";

const args = parseArgs(Deno.args, {
    boolean: ["dev", "d", "package", "clean", "fonts"],
    alias: { d: "dev" },
    negatable: ["fonts"],
    default: { fonts: true },
});

const isDev = args.dev || args.d || false;
const shouldPackage = args.package || !isDev;
const cleanOnly = args.clean || false;
const shouldBundleFonts = args.fonts !== false;

const outDir = isDev ? "dist/dev" : "dist/release";

// 1. Clean Output Directories
async function clean(): Promise<void> {
    try {
        await Deno.remove("build", { recursive: true });
    } catch {
        /* ignore */
    }
    try {
        await Deno.remove(outDir, { recursive: true });
    } catch {
        /* ignore */
    }
    console.log(`✓ Cleaned ${outDir} and build/`);
}

if (cleanOnly) {
    await clean();
    Deno.exit(0);
}

await clean();

// 2. Prepare Directories
await Deno.mkdir(`${outDir}/vendor`, { recursive: true });
await Deno.mkdir(`${outDir}/src/styles`, { recursive: true });
if (shouldBundleFonts) {
    await Deno.mkdir(`${outDir}/vendor/fonts`, { recursive: true });
}

// 3. Generate Typed Environment Module (src/env.ts)
const manifestRaw = await Deno.readTextFile("src/manifest.json");
const manifest = JSON.parse(manifestRaw);
const baseVersion = manifest.version || "0.1.3";

const now = new Date();
const pad = (n: number) => String(n).padStart(2, "0");
const buildTimestamp = `${now.getFullYear().toString().slice(-2)}${pad(now.getMonth() + 1)}${pad(now.getDate())}.${
    pad(now.getHours())
}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
const buildVersion = isDev ? `${baseVersion}-dev.${buildTimestamp}` : baseVersion;

const envFileContent = `// Automatically generated by build.ts - DO NOT EDIT MANUALLY
export const __DEV__: boolean = ${isDev};
export const __BUILD_VERSION__: string = "${buildVersion}";
`;
await Deno.writeTextFile("src/env.ts", envFileContent);
console.log(`✓ Generated src/env.ts (__DEV__ = ${isDev}, version = "${buildVersion}")`);

// 4. Compile Tailwind CSS v4 & Generate Inlined Module (In-Process)
async function compileTailwind(outDir: string, isDev: boolean): Promise<string> {
    console.log(`Compiling Tailwind CSS v4 in-process (${isDev ? "development" : "minified"})...`);

    // 1. Scan candidate tokens from TypeScript / Preact sources
    const scanner = new Scanner({
        sources: [{
            base: Deno.cwd(),
            pattern: "src/**/*.{tsx,ts,html}",
            negated: false,
        }],
    });
    const candidates = scanner.scan();

    // 2. Read Tailwind CSS entrypoint
    const inputCss = await Deno.readTextFile("src/styles/tailwind.css");

    // 3. Compile candidates with Deno-native loader
    const compiler = await compile(inputCss, {
        base: Deno.cwd(),
        onDependency: () => {},
    });
    const rawCss = compiler.build(candidates);

    // 4. Optimize / Minify
    const optimized = optimize(rawCss, { minify: !isDev });
    const finalCss = optimized.code;

    // 5. Output CSS file and generated TypeScript constant
    const cssOutFile = `${outDir}/src/styles/tailwind.css`;
    await Deno.writeTextFile(cssOutFile, finalCss);

    const generatedModuleContent = `// Automatically generated by build.ts - DO NOT EDIT MANUALLY
export const TAILWIND_CSS: string = ${JSON.stringify(finalCss)};
`;
    await Deno.writeTextFile("src/styles/tailwind.generated.ts", generatedModuleContent);

    console.log(
        `✓ Compiled and inlined Tailwind CSS (${
            (finalCss.length / 1024).toFixed(1)
        } KB) into src/styles/tailwind.generated.ts`,
    );
    return finalCss;
}

await compileTailwind(outDir, isDev);

// 5. Process and Inline KaTeX CSS & Bundle Fonts
let processedKatexCss = "";
const bundledFontFiles: string[] = [];

try {
    const rawKatexCss = await Deno.readTextFile("vendor/katex.min.css");
    if (shouldBundleFonts) {
        const fontDir = "vendor/fonts";
        for await (const entry of Deno.readDir(fontDir)) {
            if (entry.isFile && entry.name.endsWith(".woff2")) {
                await Deno.copyFile(`${fontDir}/${entry.name}`, `${outDir}/vendor/fonts/${entry.name}`);
                bundledFontFiles.push(entry.name);
            }
        }
        bundledFontFiles.sort();
        processedKatexCss = rawKatexCss.replaceAll("url(fonts/", "url(__KATEX_FONTS_ROOT__/");
        console.log(`✓ Bundled ${bundledFontFiles.length} KaTeX WOFF2 fonts into ${outDir}/vendor/fonts`);
    } else {
        processedKatexCss = rawKatexCss.replace(/@font-face\s*\{[^}]*\}/g, "");
        console.log("✓ KaTeX font bundling disabled (--no-fonts); stripped @font-face rules");
    }

    const katexGeneratedContent = `// Automatically generated by build.ts - DO NOT EDIT MANUALLY
export const KATEX_FONTS_BUNDLED: boolean = ${shouldBundleFonts};
export const KATEX_CSS: string = ${JSON.stringify(processedKatexCss)};
`;
    await Deno.writeTextFile("src/styles/katex.generated.ts", katexGeneratedContent);
    await Deno.writeTextFile(`${outDir}/vendor/katex.min.css`, processedKatexCss);
    console.log(`✓ Generated src/styles/katex.generated.ts (${(processedKatexCss.length / 1024).toFixed(1)} KB)`);
} catch (e) {
    console.warn("Notice: KaTeX processing encountered an issue:", e);
}

try {
    await Deno.copyFile("src/styles/globals.css", `${outDir}/src/styles/globals.css`);
} catch (e) {
    console.warn("Notice: stylesheet copy skipped:", e);
}

try {
    await Deno.mkdir(`${outDir}/assets`, { recursive: true });
    await Deno.copyFile("src/assets/icon.svg", `${outDir}/assets/icon.svg`);
    console.log(`✓ Copied extension icon into ${outDir}/assets/icon.svg`);
} catch (e) {
    console.warn("Notice: assets copy skipped:", e);
}

// 6. Compile Host-Specific Gemini Layout CSS via Tailwind
try {
    const rawGeminiLayoutCss = await Deno.readTextFile("src/chat/gemini/styles/layout.css");
    const layoutCompiler = await compile(rawGeminiLayoutCss, {
        base: Deno.cwd(),
        onDependency: () => {},
    });
    const builtGeminiLayoutCss = layoutCompiler.build([]);
    const optimizedGeminiLayoutCss = optimize(builtGeminiLayoutCss, { minify: !isDev }).code;
    const geminiLayoutGenerated = `// Automatically generated by build.ts - DO NOT EDIT MANUALLY
export const GEMINI_LAYOUT_CSS: string = ${JSON.stringify(optimizedGeminiLayoutCss)};
`;
    await Deno.writeTextFile("src/chat/gemini/styles/layout.generated.ts", geminiLayoutGenerated);
    console.log(
        `✓ Compiled Gemini layout CSS (${
            (optimizedGeminiLayoutCss.length / 1024).toFixed(1)
        } KB) into src/chat/gemini/styles/layout.generated.ts`,
    );
} catch (e) {
    console.warn("Notice: Gemini layout CSS compilation failed:", e);
}

// 7. Bundle with Native Deno 2 Bundle (Code-Splitting)
console.log(`Bundling with native deno bundle (${isDev ? `DEV: ${buildVersion}` : `PROD: ${buildVersion}`})...`);

const bundleArgs = [
    "bundle",
    "--platform",
    "browser",
    "--code-splitting",
    "--outdir",
    outDir,
];

if (isDev) {
    bundleArgs.push("--sourcemap", "inline");
} else {
    bundleArgs.push("--minify");
}

bundleArgs.push("src/entrypoints/app.ts");
bundleArgs.push("src/entrypoints/background.ts");

const bundleCmd = new Deno.Command("deno", {
    args: bundleArgs,
});
const bundleOutput = await bundleCmd.output();

if (bundleOutput.code !== 0) {
    const errorText = new TextDecoder().decode(bundleOutput.stderr);
    console.error("Bundle failed:\n", errorText);
    Deno.exit(bundleOutput.code);
}

console.log(`✓ Successfully bundled app.js, background.js, and split chunks into ${outDir}`);

// 7. Enumerate Explicit Chunks & Generate Manifest (No Wildcards)
const generatedChunks: string[] = [];
for await (const entry of Deno.readDir(outDir)) {
    if (
        entry.isFile && entry.name.endsWith(".js") &&
        entry.name !== "content.js" &&
        entry.name !== "background.js"
    ) {
        generatedChunks.push(entry.name);
    }
}
generatedChunks.sort();

manifest.version = baseVersion;
manifest.description = isDev ? `[DEV ${buildTimestamp}] ${manifest.description}` : manifest.description;

manifest.action = {
    default_title: "AI Chat UI Improvements",
    default_icon: "assets/icon.svg",
};

manifest.icons = {
    "48": "assets/icon.svg",
    "96": "assets/icon.svg",
    "128": "assets/icon.svg",
};

manifest.background = {
    scripts: ["background.js"],
    type: "module",
};

manifest.permissions = [
    "storage",
    "activeTab",
    "tabs",
];

manifest.content_scripts = [
    {
        matches: ["https://gemini.google.com/*", "https://duck.ai/*"],
        css: ["vendor/katex.min.css", "src/styles/globals.css"],
        run_at: "document_start",
    },
    {
        matches: ["https://gemini.google.com/*"],
        js: ["content.js"],
        run_at: "document_start",
    },
];

const webAccessibleResources: string[] = [
    ...(generatedChunks.length > 0 ? generatedChunks : ["app.js"]),
];
if (shouldBundleFonts && bundledFontFiles.length > 0) {
    for (const fontName of bundledFontFiles) {
        webAccessibleResources.push(`vendor/fonts/${fontName}`);
    }
}
webAccessibleResources.sort();

manifest.web_accessible_resources = [
    {
        resources: webAccessibleResources,
        matches: ["https://gemini.google.com/*", "https://duck.ai/*"],
    },
];

await Deno.writeTextFile(`${outDir}/manifest.json`, JSON.stringify(manifest, null, 2));
console.log(`✓ Generated manifest.json with explicit resources (${webAccessibleResources.length} items)`);

// 8. Write MV3 Dynamic Import Bootloader (content.js)
const bootloaderCode = `// Dynamic Import Bootloader for WebExtension MV3
(async () => {
  try {
    const src = (typeof browser !== "undefined" && browser.runtime?.getURL)
      ? browser.runtime.getURL("app.js")
      : "./app.js";
    await import(src);
  } catch (err) {
    console.error("[AI Chat UI] Bootloader failed to load app.js:", err);
  }
})();
`;
await Deno.writeTextFile(`${outDir}/content.js`, bootloaderCode);
console.log(`✓ Created dynamic bootloader: ${outDir}/content.js`);

// 9. Package Release Archive via 7z
if (shouldPackage) {
    const zipFileName = isDev ? `ai-chat-ui-${buildVersion}.zip` : `ai-chat-ui-${baseVersion}.zip`;

    try {
        const p7zCmd = new Deno.Command("7z", {
            args: ["a", "-tzip", "-mx=9", "-aoa", "-bd", zipFileName, "."],
            cwd: outDir,
        });
        const { code: p7zCode } = await p7zCmd.output();
        if (p7zCode === 0) {
            console.log(`✓ Created release archive via 7z: ${outDir}/${zipFileName}`);
        } else {
            console.warn("Warning: 7z exited with non-zero code, archive skipped");
        }
    } catch (e) {
        console.warn("Notice: 7z command unavailable, zip packaging skipped:", e);
    }
}
